// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dis-redirect-proxy/clients"
	"github.com/ONSdigital/dp-healthcheck/healthcheck"
	"sync"
)

// Ensure, that RedisClientMock does implement clients.RedisClient.
// If this is not the case, regenerate this file with moq.
var _ clients.RedisClient = &RedisClientMock{}

// RedisClientMock is a mock implementation of clients.RedisClient.
//
//	func TestSomethingThatUsesRedisClient(t *testing.T) {
//
//		// make and configure a mocked clients.RedisClient
//		mockedRedisClient := &RedisClientMock{
//			CheckerFunc: func(ctx context.Context, state *healthcheck.CheckState) error {
//				panic("mock out the Checker method")
//			},
//			GetValueFunc: func(ctx context.Context, key string) (string, error) {
//				panic("mock out the GetValue method")
//			},
//		}
//
//		// use mockedRedisClient in code that requires clients.RedisClient
//		// and then make assertions.
//
//	}
type RedisClientMock struct {
	// CheckerFunc mocks the Checker method.
	CheckerFunc func(ctx context.Context, state *healthcheck.CheckState) error

	// GetValueFunc mocks the GetValue method.
	GetValueFunc func(ctx context.Context, key string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Checker holds details about calls to the Checker method.
		Checker []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// State is the state argument value.
			State *healthcheck.CheckState
		}
		// GetValue holds details about calls to the GetValue method.
		GetValue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
	}
	lockChecker  sync.RWMutex
	lockGetValue sync.RWMutex
}

// Checker calls CheckerFunc.
func (mock *RedisClientMock) Checker(ctx context.Context, state *healthcheck.CheckState) error {
	if mock.CheckerFunc == nil {
		panic("RedisClientMock.CheckerFunc: method is nil but RedisClient.Checker was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		State *healthcheck.CheckState
	}{
		Ctx:   ctx,
		State: state,
	}
	mock.lockChecker.Lock()
	mock.calls.Checker = append(mock.calls.Checker, callInfo)
	mock.lockChecker.Unlock()
	return mock.CheckerFunc(ctx, state)
}

// CheckerCalls gets all the calls that were made to Checker.
// Check the length with:
//
//	len(mockedRedisClient.CheckerCalls())
func (mock *RedisClientMock) CheckerCalls() []struct {
	Ctx   context.Context
	State *healthcheck.CheckState
} {
	var calls []struct {
		Ctx   context.Context
		State *healthcheck.CheckState
	}
	mock.lockChecker.RLock()
	calls = mock.calls.Checker
	mock.lockChecker.RUnlock()
	return calls
}

// GetValue calls GetValueFunc.
func (mock *RedisClientMock) GetValue(ctx context.Context, key string) (string, error) {
	if mock.GetValueFunc == nil {
		panic("RedisClientMock.GetValueFunc: method is nil but RedisClient.GetValue was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockGetValue.Lock()
	mock.calls.GetValue = append(mock.calls.GetValue, callInfo)
	mock.lockGetValue.Unlock()
	return mock.GetValueFunc(ctx, key)
}

// GetValueCalls gets all the calls that were made to GetValue.
// Check the length with:
//
//	len(mockedRedisClient.GetValueCalls())
func (mock *RedisClientMock) GetValueCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockGetValue.RLock()
	calls = mock.calls.GetValue
	mock.lockGetValue.RUnlock()
	return calls
}
