name: Audit

permissions:
  contents: read

on:
  schedule:
    - cron: 0 0 */14 * *
  workflow_dispatch:

# Single source of truth for tool versions
env:
  GO_VERSION: '1.26.5'
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  dis-redirect-proxy-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      - name: Install dis-vulncheck
        run: go install github.com/ONSdigital/dis-vulncheck@latest
      - name: Run dis-vulncheck
        run: make audit
      - name: Slack notification on failure
        # Only notify failures for periodic runs on main branch
        if: failure() && env.BRANCH_NAME == 'main'
        uses: slackapi/slack-github-action@45a88b9581bfab2566dc881e2cd66d334e621e2c # v3.0.3
        with:
          channel-id: ci-failures
          payload: |
            {
              "text": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|audit test ${{ github.run_id }}> failed for <${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}> branch `${{ env.BRANCH_NAME }}`"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
